### ISSUE TITLE
Like the concepts but adding trojan to the package is not cool at all.

### ISSUE THREAD

**Issue by kenny-ngo** [chand1012/winguake#2]
I reluctantly reject this project.

Ref: https://www.virustotal.com/gui/file/9cd133529e8994bd9b00cac205204e824b6d5087088bcd25c752de03f04d8cf9/detection

**Comment by chand1012** [comment]
The trojan is there because most antivirus software will freak out if it sees autohotkey scripts. Please see the source code for what everything does. If the executable is triggering antivirus I may just have to remove it and have people compile it themselves.
